### ISSUE TITLE
Issue 1 User can search for cards by name

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/marketmon#1]
## 💰 Motivation

If a user types in the name of a pokemon in the search bar, they should be able to see a list of search results of cards whose name matches the search criteria.

## 📐 Plan

Allow users to search for a card in the search bar.

## 🖼️ Wireframes

![Search Results Mobile](https://github.com/vanessaviray/front-end-project/assets/161077888/11aa41a2-a19e-4aa3-9c7a-b25c870347ec)
![Search Results Desktop](https://github.com/vanessaviray/front-end-project/assets/161077888/a3ff3fd8-e080-41ea-aad3-69c43e6f3d88)

## ✅ Task List
- [x] add an anchor that displays the website's logo
- [x] when the user clicks **logo**, swap to Welcome Page view
- [x] add an input element whose default state contains a magnifying glass icon and the placeholder 'Search for card by name'
- [x] when the user searches a card name:
  - [x] swap to Search Results view
  - [x] display all card objects from the api whose name matches the search criteria submitted in the input element:
    - [x] create a function to fetch matching card objects from the api
    - [x] create a card info object that stores the values of the card image, the card name, the set name, the card number, and the current market value
    - [x] create a DOM tree to render card info objects
    - [x] call a function that will display a message indicating there are no matches if no results are rendered
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
