### ISSUE TITLE
Issue 2 User can add card to collection

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/marketmon#2]
## 💰 Motivation

If a user decides that they want to include a specific card in their collection, they should be able to add that card to their collection.

## 📐 Plan

Allow users to add a card to their collection from by clicking the plus button in each individual card object in the Search Results view

## 🖼️ Wireframes

![Card Added Alert Mobile](https://github.com/vanessaviray/front-end-project/assets/161077888/ab4cd896-0b25-45e3-9efa-159a7a92256f)
![Card Added Alert Desktop](https://github.com/vanessaviray/front-end-project/assets/161077888/2396ea85-efd2-4b99-be56-7b6dba25e272)

## ✅ Task List
- [x] create a view for 'my-collection'
- [x] create event listener for the 'My Collection' button that will perform the following actions:
  - [x] calls the viewSwap function to swap to the 'my-collection' view
  - [x] clears the text content in the search bar
- [x] create an event listener for the '+' icon that will perform the following actions:
  - [x] calls a function that creates an alert to indicate that the card was successfully added
  - [x] calls a function that prepends the data of the targeted cardInfo object in an array that is stored in local storage
- [x] in the event listener for the 'My Collection' button add these additional actions:
  - [x]  a call for a function that generates and renders a DOM tree of the array of cardInfo objects in local storage
    - [x] this is to be displayed in the 'my-collection' view
    - [x] replace the '+' icon to a '-' icon
