### ISSUE TITLE
Issue 3 User can delete card from collection

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/marketmon#3]
## 💰 Motivation

If a user decides that they no longer want to include a specific card in their collection, they should be able to remove that card from their collection.

## 📐 Plan

Allow users to remove a card from their collection by clicking the minus button in the My Collection view.

## 🖼️ Wireframes

<img width="375" alt="Remove Modal Mobile" src="https://github.com/vanessaviray/front-end-project/assets/161077888/aefa09f6-6d92-4e53-ad55-e824011f6c3b">

![Remove Card Modal Desktop](https://github.com/vanessaviray/front-end-project/assets/161077888/a7de6705-651b-4326-891e-fc64330b9f80)

## ✅ Task List
- [x] add event listener for when the user clicks the '-' button that displays the modal asking the user to confirm if they want to remove the card from their collection
- [x] add event listener to the 'x' icon to close the modal
- [x] add event listener for when the user clicks the confirm remove button to perform the following actions:
  - [x] close the modal
  - [x] removes the card from the collection
  - [x] alerts that the card has been successfully removed
- [x] add event listener for when the user clicks the cancel button to close the modal
