### ISSUE TITLE
Issue 4 User can read list of cards and total market value of collection

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/marketmon#4]
## 💰 Motivation

If a user decides that they want to view their collection, they should be able to see a list of all the cards they have previously added to their collection.

## 📐 Plan

Allow users to view their collection by clicking on the 'My Collection' button

## 🖼️ Wireframes

<img width="375" alt="My Collection Mobile" src="https://github.com/vanessaviray/front-end-project/assets/161077888/eb451ffb-c8f3-4498-8481-d092dcfafc31">

![My Collection Desktop](https://github.com/vanessaviray/front-end-project/assets/161077888/3784dce4-1d69-4c5e-99d7-ebf2b033f3f6)

## ✅ Task List
- [x] edit 'my-collection' view to:
  - [x] display price of total market value of collection
- [x] display message when there are no cards in the collection
