### ISSUE TITLE
Issue 5 User can read additional details and larger image of card

### ISSUE THREAD

**Issue by vanessaviray** [vanessaviray/marketmon#6]
## 💰 Motivation

If a user decides that they want to more information about a card, they should be able to view a larger image of that card and read additional details about that card.

## 📐 Plan

Allow users to view Card Details by clicking on one of the card objects in the Search Results view or the My Collection view

## 🖼️ Wireframes

<img width="375" alt="Card Details Mobile" src="https://github.com/vanessaviray/front-end-project/assets/161077888/e844c116-a28d-416e-9c34-7d2335a68331">

![Card Details Desktop](https://github.com/vanessaviray/front-end-project/assets/161077888/ac6b3c76-2d9e-4110-8b86-b7b0637af872)

## ✅ Task List
- [x] create a new view 'card-details':
- [x] add event listener to show 'card-details' view when a card in the 'search-results' view is clicked
  - [x] when the user exits out of the card details, swap views back to 'search-results' (account for previous scroll position)
  - [x] add event listener to card details button to add card to the collection
- [x] add event listener to show 'card-details' view when a card in the 'my-collection' view is clicked
  - [x] when the user exits out of the card details, swap views back to 'my-collection' (account for previous scroll position)
  - [x] add event listener to card details button to add card to the collection
  - [x] collection should immediately update
